runtime: python27
threadsafe: true
service: default
handlers:
  - url: /
    static_files: gcp-sandbox-ui/index.html
    upload: gcp-sandbox-ui/index.html
  - url: /
    static_dir: gcp-sandbox-ui
manual_scaling:
  instances: 1
