runtime: python27
threadsafe: true
service: default
handlers:
  - url: /
    static_files: index.html
    upload: index.html
  - url: /
    static_dir: .
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
manual_scaling:
  instances: 1
