name: CICD

on:
  push:
    branches: [main]

jobs:
  cicd:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download npm dependencies
        run: npm ci
        working-directory: ui
      - name: Build
        run: ng build
        working-directory: ui
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: '/ui/dist/gcp-sandbox-ui'
          destination: 'gcp.dfar.io'
