name: CICD

on:
  push:
    branches: [main]

jobs:
  cicd:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Download npm dependencies
        run: npm ci
        working-directory: ui
      - name: Build
        run: npm run ng build
        working-directory: ui
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      - name: 'Upload to Storage Bucket'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'ui/dist/gcp-sandbox-ui'
          destination: 'gcp.dfar.io'
          # places contents directly into bucket, instead of folder
          parent: false
          # prevents caching of site through GCP
          headers: |-
            x-goog-meta-Cache-Control: no-cache, max-age=0
