name: Apply Infrastructure Changes

on:
  workflow_dispatch:
    inputs:
      should-apply:
        description: "Type 'yes' to apply changes found."

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_Name }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Initialize Terraform
        run: terraform init
        working-directory: infra
      - name: Run Terraform Plan
        run: terraform plan -out tfplan
        working-directory: infra
      - name: Apply Terraform Changes
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.should-apply == 'yes' }}
        run: terraform apply "tfplan"
        working-directory: infra
      
    
