name: Apply Infrastructure Changes

on:
  workflow_dispatch:
    inputs:
      should-apply:
        description: "Type 'yes' to apply changes found."

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'github-actions@gcp-sandbox-368017.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: Initialize Terraform
        run: terraform init
        working-directory: infra
      - name: Run Terraform Plan
        run: terraform plan -out tfplan
        working-directory: infra
      - name: Apply Terraform Changes
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.should-apply == 'yes' }}
        run: terraform apply "tfplan"
        working-directory: infra
      
    
